/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author MEENA
 */
public class Delete extends javax.swing.JFrame {

    /**
     * Creates new form Delete
     */
    public Delete() {
        initComponents();
        delete.setVisible(false);
        empdetail.setVisible(false);
        deleted.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        signout = new javax.swing.JButton();
        deleted = new javax.swing.JButton();
        mainframe = new javax.swing.JPanel();
        empdetail = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        empname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        empdep = new javax.swing.JTextField();
        extra = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        select = new javax.swing.JPanel();
        clothgo = new javax.swing.JTextField();
        empid = new javax.swing.JTextField();
        clab = new javax.swing.JLabel();
        cgo = new javax.swing.JButton();
        go = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Forte", 1, 36)); // NOI18N
        jLabel1.setText("Clothing Entrepreneurship");

        signout.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        signout.setText("Sign out");
        signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutActionPerformed(evt);
            }
        });

        deleted.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deleted.setForeground(java.awt.Color.red);
        deleted.setText("Deleted !!!");
        deleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletedActionPerformed(evt);
            }
        });

        empdetail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N

        id.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        delete.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel5.setText("Department");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel3.setText("Employee Name");

        empname.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel4.setText("Employee Id");

        empdep.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        javax.swing.GroupLayout empdetailLayout = new javax.swing.GroupLayout(empdetail);
        empdetail.setLayout(empdetailLayout);
        empdetailLayout.setHorizontalGroup(
            empdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empdetailLayout.createSequentialGroup()
                .addGroup(empdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empdetailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(empdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(empdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empname, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empdep, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(empdetailLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        empdetailLayout.setVerticalGroup(
            empdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empdetailLayout.createSequentialGroup()
                .addGroup(empdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(empdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(empdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empdep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete))
        );

        javax.swing.GroupLayout mainframeLayout = new javax.swing.GroupLayout(mainframe);
        mainframe.setLayout(mainframeLayout);
        mainframeLayout.setHorizontalGroup(
            mainframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainframeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empdetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        mainframeLayout.setVerticalGroup(
            mainframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainframeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(empdetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        back.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        empid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        clab.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        clab.setText("Cloth Id       :");

        cgo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cgo.setText("Go");
        cgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgoActionPerformed(evt);
            }
        });

        go.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        go.setText("Go");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setText("Employee Id :");

        javax.swing.GroupLayout selectLayout = new javax.swing.GroupLayout(select);
        select.setLayout(selectLayout);
        selectLayout.setHorizontalGroup(
            selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clab)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(empid)
                    .addComponent(clothgo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(go, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cgo))
                .addContainerGap())
        );
        selectLayout.setVerticalGroup(
            selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(go)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clothgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cgo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(signout))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mainframe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(293, 293, 293)
                                .addComponent(deleted)))
                        .addGap(113, 113, 113)
                        .addComponent(extra, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(extra, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(deleted)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainframe, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(back)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

         Page2 p2=new Page2();
        p2.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutActionPerformed
           NewLogin n=new NewLogin();
           n.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_signoutActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
  String url="jdbc:mysql://localhost:3306/project2014?zeroDateTimeBehavior=convertToNull";
        String driver="com.mysql.jdbc.Driver";
        String username="root";
        String password="meena.";
    try{
        Class.forName(driver).newInstance();
        Connection conn ;
        conn = DriverManager.getConnection(url,username,password);
        ResultSet rs;
        String str="delete from t20 where emp_id=?";
        PreparedStatement ps=conn.prepareStatement(str);        
        String id=empid.getText();
        ps.setString(1, id);

        
        /*        String e_id=empid.getText();
        String str="select emp_name from t20 where emp_id=?";
        PreparedStatement ps=conn.prepareStatement(str);
        ps.setString(1,e_id );
        empname.setText(str);
  */      mainframe.setVisible(false);
        deleted.setVisible(true);
// JOptionPane.showMessageDialog(null, "Deleted");
    }
          catch(ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException e){
      System.err.println(e.getMessage()); 
     // JOptionPane.showMessageDialog(null, e);
    }   
    
  }                                          

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {                                      
        
        Insert in=new Insert();
        in.setVisible(true);
                       // TODO add your handling code here:
    }                                     

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {                                        
        Insert in=new Insert();
        in.setVisible(true);
                // TODO add your handling code here:
    }                                       

    private void rawsubmitActionPerformed(java.awt.event.ActionEvent evt) {                                          
 
    }//GEN-LAST:event_deleteActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
         String url="jdbc:mysql://localhost:3306/project2014?zeroDateTimeBehavior=convertToNull";
        String driver="com.mysql.jdbc.Driver";
        String username="root";
        String password="meena.";
    try{
        Class.forName(driver).newInstance();
        Connection conn ;
        conn = DriverManager.getConnection(url,username,password);
        ResultSet rs1;
        ResultSet rs2;
        Statement s=conn.createStatement();
        String emplid=empid.getText();
        rs1=s.executeQuery("select emp_name from t20 where emp_id ='"+emplid+"';");
       
        empdetail.setVisible(true);
        delete.setVisible(true);
       
        while(rs1.next())     
        {String st = rs1.getString("emp_name");
        empname.setText(st);
        }
        rs2=s.executeQuery("select dep_id from t20 where emp_id ='"+emplid+"';");
        while(rs2.next())
        {
            String st1=rs2.getString("dep_id");
            empdep.setText(st1);
            
        }id.setText(emplid);
        
            /*      String e_id=empid.getText();
        String str="select emp_name from t20 where emp_id=?";
        
        PreparedStatement ps=conn.prepareStatement(str);
        ps.setString(1,e_id );
        empname.setText(str);
  */
        
        
        
    }
          catch(ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException e){
      System.err.println(e.getMessage()); 
     // JOptionPane.showMessageDialog(null, e);
     }
// TODO add your handling code here:
    }//GEN-LAST:event_goActionPerformed

    private void deletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedActionPerformed
Page2 p2=new Page2();
p2.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_deletedActionPerformed

    private void cgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgoActionPerformed
  String url="jdbc:mysql://localhost:3306/project2014?zeroDateTimeBehavior=convertToNull";
        String driver="com.mysql.jdbc.Driver";
        String username="root";
        String password="meena.";
    try{
        Class.forName(driver).newInstance();
        Connection conn ;
        conn = DriverManager.getConnection(url,username,password);
        ResultSet rs;
        String str="delete from t17 where cloth_id=?";
        PreparedStatement ps=conn.prepareStatement(str);        
        String id=clothgo.getText();
        ps.setString(1, id);
        ps.execute();
     // clothgo.setVisible(false);
        select.setVisible(false);
        mainframe.setVisible(false);
        deleted.setVisible(true);
// JOptionPane.showMessageDialog(null, "Deleted");
    }
          catch(ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException e){
      System.err.println(e.getMessage()); 
     // JOptionPane.showMessageDialog(null, e);
    }   
        // TODO add your handling code here:
    }//GEN-LAST:event_cgoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton cgo;
    private javax.swing.JLabel clab;
    private javax.swing.JTextField clothgo;
    private javax.swing.JButton delete;
    private javax.swing.JButton deleted;
    private javax.swing.JTextField empdep;
    private javax.swing.JPanel empdetail;
    private javax.swing.JTextField empid;
    private javax.swing.JTextField empname;
    private javax.swing.JLabel extra;
    private javax.swing.JButton go;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel mainframe;
    private javax.swing.JPanel select;
    private javax.swing.JButton signout;
    // End of variables declaration//GEN-END:variables
}
